### PR TITLE
Add Nalin to opensourcedesign

### PR DESCRIPTION
**Pull request by Nalinc**

### CODE REVIEW

**Comment by myckyc** [comment]
Welcome onboard @Nalinc

**Comment by Nalinc** [comment]
@myckyc Thanks :)

I'm still waiting for the invite to _github organisation_. Could you send that too ? :)
cc: @gillisig

**Comment by myckyc** [comment]
@Nalinc sorry I can't. This function is available only for owners I believe. You can ask them here or on an IRC channel.

**Comment by simonv3** [comment]
@Nalinc just added you, welcome!

**Pull request merged**
