### PR TITLE
Adding myself to the organization/people list

### PR DESCRIPTION
**Pull request by mindreeper2420**

### CODE REVIEW

**Comment by andresgalante** [comment]
👍 
2 horses, really?

**Comment by mindreeper2420** [comment]
yup - one is about 20 years old, the other 8. They're just really big dogs :smile:

**Comment by simonv3** [comment]
👍  welcome @mindreeper2420!

**Comment by gillisig** [comment]
Hey @mindreeper2420 would you mind giving me your router password? I just want to check a few things! ;) 



P.S. Yeah you might want to fix where that https link leads :)

**Comment by mindreeper2420** [comment]
@gillisig well that's new...

**Comment by gillisig** [comment]
@mindreeper2420 Are you hosting the website on your home network?

**Comment by mindreeper2420** [comment]
@gillisig no, I'm not. It is being hosted for me.

**Comment by gillisig** [comment]
Oh, strange. Well hopefully they fix it quickly.

**Comment by priley86** [comment]
@mindreeper2420 glad to see another Patternfly guy here!!! Now if we can just get @andresgalante to join! 

👍

**Pull request merged**
