### PR TITLE
Added Julien Deswaef to the list.

### PR DESCRIPTION
**Pull request by xuv**

### CODE REVIEW

**Comment by simonv3** [comment]
@xuv Welcome! Looks like you're based in Brussels? I'm just outside of Gent :)

**Comment by xuv** [comment]
@simonv3 Hey. Thx. Yes. I still have projects in Brussels. But I just moved to NYC. :)

**Comment by jancborchardt** [comment]
@xuv I took the liberty to add you to the organization because you are involved with the whole Libre Graphics scene. :)

**Comment by xuv** [comment]
@jancborchardt Yes. Thx for that. Although I'm not sure I fully understand the scope if this github based project. And I wasn't physically present at LGM to discuss it with you. Don't know if you can point me to a text describing what you are trying to achieve here.

**Comment by jancborchardt** [comment]
@xuv basically all the info should be at http://opensourcedesign.net/ and http://opensourcedesign.net/about :) – we’re just trying to bring together the folks who work in design & open source. Push the existing initiatives, build new tools, improve the design of open source software, and make it all sustainable.

**Comment by xuv** [comment]
@jancborchardt Yes. Have read that.Thx. It's really ambitious and I like it. But it's maybe also so ambitious that I have a hard time figuring out where does it start, what are the steps, how is it going to sustain itself. It also echoes with many of the organizations that I'm already a member of that I see it as maybe yet another one. Don't want to be "de-motivational" here, but I see the work done by others and how they struggle to make it exist and they sometimes are more focused on certain aspects of open source design. Here, it seems to try to embrace a lot of things. So I'm just observing for now, and can contribute with what I'm doing, but wonders if the point here is to "gather it all" and provide a kind of hub that points to others or something else with another agenda? Maybe I should not expose all these thoughts here and just say that I'm really happy to see a group of active people trying to make open source design stronger.
Sorry for the many questions hidden in this post.

**Comment by plastelina** [comment]
@xuv You've nailed it. I do struggle with the same thoughts.

**Pull request merged**
