### PR TITLE
ADD ME!

### PR DESCRIPTION
**Pull request by rafaelstz**

### CODE REVIEW

**Comment by simonv3** [comment]
Awesome! Just one thing - frontmatter (the thing jekyll uses) freaks out when there's an @ at the beginning of a field. (your github username in this case). Can you change it to be without?

**Comment by simonv3** [comment]
(I've just done a PR on the template to reflect this)

**Comment by rafaelstz** [comment]
OK :+1: :smile:

**Comment by simonv3** [comment]
Sweet!

**Comment by rafaelstz** [comment]
@simonv3 Can be added in the organization?

**Comment by gillisig** [comment]
@rafaelstz I added you

**Pull request merged**
